config/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as error_views

from nutriologa.apps.landing import urls as landing_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Custom urls
    url(r'', include(landing_urls, namespace='landing')),
]

if settings.DEBUG:
    import debug_toolbar
    # This allows the error pages to be debugged during development, visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', error_views.bad_request, kwargs={
            'exception': Exception("Bad Request!")}),
        url(r'^403/$', error_views.permission_denied, kwargs={
            'exception': Exception("Permission Denied")}),
        url(r'^404/$', error_views.page_not_found, kwargs={
            'exception': Exception("Page not Found")}),
        url(r'^500/$', error_views.server_error),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nutriologa/apps/landing/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [

    url(regex=r'^$',
        view=views.HomeTemplateView.as_view(),
        name='home'),

    url(regex=r'^videos/$',
        view=views.VideosTemplateView.as_view(),
        name='videos'),

    url(regex=r'^contacto/$',
        view=views.ContactTemplateView.as_view(),
        name='contacto'),


    url(regex=r'^send/$',
        view=views.ContactView.as_view(),
        name='email'),

    url(regex=r'^recetas/$',
        view=views.RecipesTemplateView.as_view(),
        name='recetas'),

    url(regex=r'^acerca/$',
        view=views.AboutTemplateView.as_view(),
        name='acerca'),

    url(regex=r'^servicios/$',
        view=views.ServicesTemplateView.as_view(),
        name='servicios'),

    url(regex=r'^newsletter/$',
        view=views.NewsletterView.as_view(),
        name='newsletter'),

]

nutriologa/apps/recipes/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*
import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _



class Video(models.Model):
    title = models.CharField(
        verbose_name=_('Title'),
        max_length=500,
        blank=False,
        null=False,
    )

    youtube_video_url = models.CharField(
        verbose_name=_('Youtube URL'),
        blank=False,
        null=False,
        max_length=100,
    )

    youtube_video_id = models.CharField(
        verbose_name=_('Youtube video ID'),
        blank=True,
        null=True,
        max_length=100,
    )

    date = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        verbose_name = _('Video')
        verbose_name_plural = _('videos')

    def __str__(self):
        return self.title


class Recipe(models.Model):

    title = models.CharField(
        verbose_name=_('Title'),
        max_length=500,
        blank=False,
        null=False,
    )

    image = models.ImageField(
        verbose_name=_('Image'),
        blank=False,
        null=False,
        upload_to='recipes',
    )

    description = models.TextField(
        verbose_name=_('Description'),
        blank=False,
        null=False,
    )

    category = models.CharField(
        verbose_name=_('Category'),
        max_length=50,
        blank=False,
        null=False,
        choices=(
            ('breakfast', 'Desayuno'),
            ('collation', 'Colaciones'),
            ('meal', 'Comidas'),
            ('dinner', 'Cenas'),
        )
    )

    date = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        verbose_name = _('Recipe')
        verbose_name_plural = _('Recipes')

    def __str__(self):
        return self.title

nutriologa/apps/wordpress/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desidered behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class WpCommentmeta(models.Model):
    meta_id = models.BigIntegerField(primary_key=True)
    comment_id = models.BigIntegerField()
    meta_key = models.CharField(max_length=255, blank=True, null=True)
    meta_value = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'wp_commentmeta'


class WpComments(models.Model):
    comment_id = models.BigIntegerField(db_column='comment_ID', primary_key=True)  # Field name made lowercase.
    comment_post_id = models.BigIntegerField(db_column='comment_post_ID')  # Field name made lowercase.
    comment_author = models.TextField()
    comment_author_email = models.CharField(max_length=100)
    comment_author_url = models.CharField(max_length=200)
    comment_author_ip = models.CharField(db_column='comment_author_IP', max_length=100)  # Field name made lowercase.
    comment_date = models.DateTimeField()
    comment_date_gmt = models.DateTimeField()
    comment_content = models.TextField()
    comment_karma = models.IntegerField()
    comment_approved = models.CharField(max_length=20)
    comment_agent = models.CharField(max_length=255)
    comment_type = models.CharField(max_length=20)
    comment_parent = models.BigIntegerField()
    user_id = models.BigIntegerField()

    class Meta:
        managed = False
        db_table = 'wp_comments'


class WpLinks(models.Model):
    link_id = models.BigIntegerField(primary_key=True)
    link_url = models.CharField(max_length=255)
    link_name = models.CharField(max_length=255)
    link_image = models.CharField(max_length=255)
    link_target = models.CharField(max_length=25)
    link_description = models.CharField(max_length=255)
    link_visible = models.CharField(max_length=20)
    link_owner = models.BigIntegerField()
    link_rating = models.IntegerField()
    link_updated = models.DateTimeField()
    link_rel = models.CharField(max_length=255)
    link_notes = models.TextField()
    link_rss = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'wp_links'


class WpOptions(models.Model):
    option_id = models.BigIntegerField(primary_key=True)
    option_name = models.CharField(unique=True, max_length=191)
    option_value = models.TextField()
    autoload = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'wp_options'


class WpPostmeta(models.Model):
    meta_id = models.BigIntegerField(primary_key=True)
    post_id = models.BigIntegerField()
    meta_key = models.CharField(max_length=255, blank=True, null=True)
    meta_value = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'wp_postmeta'


class WpPosts(models.Model):
    id = models.BigIntegerField(db_column='ID', primary_key=True)  # Field name made lowercase.
    post_author = models.BigIntegerField()
    post_date = models.DateTimeField()
    post_date_gmt = models.DateTimeField()
    post_content = models.TextField()
    post_title = models.TextField()
    post_excerpt = models.TextField()
    post_status = models.CharField(max_length=20)
    comment_status = models.CharField(max_length=20)
    ping_status = models.CharField(max_length=20)
    post_password = models.CharField(max_length=255)
    post_name = models.CharField(max_length=200)
    to_ping = models.TextField()
    pinged = models.TextField()
    post_modified = models.DateTimeField()
    post_modified_gmt = models.DateTimeField()
    post_content_filtered = models.TextField()
    post_parent = models.BigIntegerField()
    guid = models.CharField(max_length=255)
    menu_order = models.IntegerField()
    post_type = models.CharField(max_length=20)
    post_mime_type = models.CharField(max_length=100)
    comment_count = models.BigIntegerField()

    class Meta:
        managed = False
        db_table = 'wp_posts'

    def __unicode__(self):
        return self.post_title


class WpTermRelationships(models.Model):
    object_id = models.BigIntegerField()
    term_taxonomy_id = models.BigIntegerField()
    term_order = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'wp_term_relationships'
        unique_together = (('object_id', 'term_taxonomy_id'),)


class WpTermTaxonomy(models.Model):
    term_taxonomy_id = models.BigIntegerField(primary_key=True)
    term_id = models.BigIntegerField()
    taxonomy = models.CharField(max_length=32)
    description = models.TextField()
    parent = models.BigIntegerField()
    count = models.BigIntegerField()

    class Meta:
        managed = False
        db_table = 'wp_term_taxonomy'
        unique_together = (('term_id', 'taxonomy'),)


class WpTermmeta(models.Model):
    meta_id = models.BigIntegerField(primary_key=True)
    term_id = models.BigIntegerField()
    meta_key = models.CharField(max_length=255, blank=True, null=True)
    meta_value = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'wp_termmeta'


class WpTerms(models.Model):
    term_id = models.BigIntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200)
    term_group = models.BigIntegerField()

    class Meta:
        managed = False
        db_table = 'wp_terms'


class WpUsermeta(models.Model):
    umeta_id = models.BigIntegerField(primary_key=True)
    user_id = models.BigIntegerField()
    meta_key = models.CharField(max_length=255, blank=True, null=True)
    meta_value = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'wp_usermeta'


class WpUsers(models.Model):
    id = models.BigIntegerField(db_column='ID', primary_key=True)  # Field name made lowercase.
    user_login = models.CharField(max_length=60)
    user_pass = models.CharField(max_length=255)
    user_nicename = models.CharField(max_length=50)
    user_email = models.CharField(max_length=100)
    user_url = models.CharField(max_length=100)
    user_registered = models.DateTimeField()
    user_activation_key = models.CharField(max_length=255)
    user_status = models.IntegerField()
    display_name = models.CharField(max_length=250)

    class Meta:
        managed = False
        db_table = 'wp_users'

nutriologa/apps/recipes/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms

from nutriologa.apps.recipes.models import Video

class VideoForm(forms.ModelForm):

    def save(self, commit=True):
        m = super(VideoForm, self).save(commit=False)
        m.youtube_video_id = m.youtube_video_url.split('/embed/')[1]
        if commit:
            m.save()
        return m

    def clean_youtube_video_url(self):
        cleaned_data = super(VideoForm, self).clean()
        url = cleaned_data.get('youtube_video_url')
        if 'embed' in url:
            embed_url = url
        elif url == '':
            embed_url = ''
        else:
            try:
                arg = url.split('=')[1]
                embed_url = 'https://www.youtube.com/embed/%s' % arg
            except:
                raise forms.ValidationError('Inserte un link de la forma https://www.youtube.com/watch?v=IVembed_url6ZlksMJw')
        return embed_url

    class Meta:
        model = Video
        fields = ['title', 'youtube_video_url', ]

nutriologa/apps/landing/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*
import json
import requests

from django.http import HttpResponse
from django.http import JsonResponse
from django.template import loader
from django.utils.decorators import method_decorator
from django.utils.text import slugify
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.views.generic import View
from django.core.mail import EmailMultiAlternatives
import urlparse

from django.conf import settings
from nutriologa.apps.wordpress.models import WpPosts, WpPostmeta
from nutriologa.apps.recipes.models import Recipe, Video


class Thumbnail():
    def __init__(self, post_id, url):
        self.post_id = post_id
        self.url = url


class AboutTemplateView(TemplateView):
    template_name = 'acerca.html'

    def get_context_data(self, **kwargs):
        context = super(AboutTemplateView, self).get_context_data(**kwargs)
        return context


class ContactTemplateView(TemplateView):
    template_name = 'contacto.html'

    def get_context_data(self, **kwargs):
        context = super(ContactTemplateView, self).get_context_data(**kwargs)
        return context


class ContactView(View):

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(ContactView, self).dispatch(request, *args, **kwargs)

    def post(self, request):
        name = request.POST.get('name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        date = request.POST.get('date')

        ctx = {
            'name': name,
            'last_name': last_name,
            'email': email,
            'phone': phone,
            'message': message,
            'date': date,
        }

        body = loader.render_to_string('email/contact.html', ctx)

        msg = EmailMultiAlternatives(
            subject="Notificacion de Contacto",
            body="Repleace with HTML",
            from_email="Contacto Desde Pagina Web <postmaster@mg.alegpaez.com>",
            to=[settings.DEFAULT_EMAIL_TO],
        )

        msg.attach_alternative(body, "text/html")

        msg.send()
        response = 'Send'

        return HttpResponse(response)


class ServicesTemplateView(TemplateView):
    template_name = 'servicios.html'

    def get_context_data(self, **kwargs):
        context = super(ServicesTemplateView, self).get_context_data(**kwargs)
        return context


class RecipesTemplateView(ListView):
    template_name = 'recetas.html'
    model = Recipe
    context_object_name = 'recipes'

    def get_queryset(self, ):
        arg = self.request.GET.get('u')
        if arg:
            queryset = self.model.objects.filter(category=arg).order_by('-date')
        else:
            queryset = self.model.objects.all().order_by('-date')
        return queryset

    def get_context_data(self, **kwargs):
        context = super(RecipesTemplateView, self).get_context_data(**kwargs)
        recipes = context.get('recipes')
        for recipe in recipes:
            description = recipe.description.replace('\n', '<br>')
            recipe.description = description
        context['recipes'] = recipes
        return context




class VideosTemplateView(TemplateView):
    template_name = 'videos.html'

    def get_context_data(self, **kwargs):
        context = super(VideosTemplateView, self).get_context_data(**kwargs)
        videos = Video.objects.all().order_by('-date')
        context['videos'] = videos
        return context


class HomeTemplateView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(HomeTemplateView, self).get_context_data(**kwargs)
        thumbnails = []
        posts = WpPosts.objects.filter(post_status='publish').order_by('-post_date')[:4]
        recipes = Recipe.objects.all().order_by('-date')[:3]
        for recipe in recipes:
            description = recipe.description.replace('\n', '<br>')
            recipe.description = description

        metas = WpPostmeta.objects.all()
        for post in posts:
            wp_date = post.post_date
            date_object = str(wp_date.date()).replace('-', '/')
            slug = slugify(post.post_title)
            url = '%s/%s/' % (date_object, slug )
            post.link = url
            for meta in metas:
                if meta.post_id == post.id and meta.meta_key == '_thumbnail_id':
                    thumbnail_id = meta.meta_value
                    thumb = WpPostmeta.objects.get(post_id=thumbnail_id, meta_key='_wp_attached_file')
                    thumbnails.append(Thumbnail(post.id, thumb.meta_value))
        for post in posts:
            for thumb in thumbnails:
                if post.id == thumb.post_id:
                    post.thumbnail = thumb.url
                    break
        context['posts'] = posts
        context['recipes'] = recipes
        context['metas'] = metas
        return context


class NewsletterView(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(NewsletterView, self)\
            .dispatch(request, *args, **kwargs)

    @staticmethod
    def post(request):
        email = request.POST.get('email')
        list_id = settings.NEWSLETTER_LIST_ID
        endpoint = urlparse.urljoin(
            settings.MAILCHIMP_API_ROOT, 'lists/%s/members/' % list_id
        )
        data = {
            "email_address": email,
            "status": "subscribed",
        }
        data = json.dumps(data)
        response = requests.post(
            endpoint, auth=('apikey', settings.MAILCHIMP_API_KEY), data=data)
        return JsonResponse(response.json())

nutriologa/templates/partials/carrousel.html
{% load static from staticfiles %}
<script >
  //Modulate

  $(document).ready(function(){
    $('.carrousel-slick').slick({
      accessibility: true,
      arrows: true,
      prevArrow: '',
      autoplay: true,
      centerMode: true,
      centerPadding: '0px',
      lazyLoad: 'ondemand',
      nextArrow: '<img class="pointer.slick-arrow-main glyph_l pointer carrousel-slick-arrow" src="{% static 'img/icons/right-arrow-64.png' %}" />'
    });
    $('.carrousel-slick').slick('refresh');
  });
</script>

<div class="carrousel-slick">

  <div style="background: url({% static 'img/slider/group-3@3x.png' %});height:479px;background-size: cover;">
    <div class="backdrop"></div>
    <div class="verticalHouse">
      <h1 class="banner_text up"> Olvídate de las dietas <br> y activa tu metabolismo </h1>
      <p class="sub_head up"> de una forma saludable y sostenible </p>
      <a href="/contacto" class="up read_more_btn">Agenda tu cita</a>
    </div>
  </div>
  <div style="background: url({% static 'img/slider/carrousel_1.jpg' %});height:479px;background-size: cover;">
    <div class="verticalHouse">
      <h1 class="banner_text up"> No se trata de comer menos</h1>
      <p class="sub_head up"> se trata de comer mejor </p>
      <a href="/contacto" class="up read_more_btn">Agenda tu cita</a>
    </div>
  </div>
  <div style="background: url({% static 'img/slider/carrousel_2.jpg' %});height:479px;background-size: cover;">
    <div class="verticalHouse">
      <h1 class="banner_text up"> Crea hábitos saludables</h1>
      <p class="sub_head up"> no restricciones</p>
      <a href="/contacto" class="up read_more_btn">Agenda tu cita</a>
    </div>
  </div>
  <div style="background: url({% static 'img/slider/carrousel_3.jpg' %});height:479px;background-size: cover;">
    <div class="verticalHouse">
      <h1 class="banner_text up"> Tu cuerpo merece lo mejor</h1>
      <a href="/contacto" class="up read_more_btn">Agenda tu cita</a>
    </div>
  </div>
  <div style="background: url({% static 'img/slider/carrousel_4.jpg' %});height:479px;background-size: cover;">
    <div class="verticalHouse">
      <h1 class="banner_text up"> Nunca es tarde para cambiar tu estilo de vida </h1>
      <a href="/contacto" class="up read_more_btn">Agenda tu cita</a>
    </div>
  </div>
  <div style="background: url({% static 'img/slider/carrousel_5.jpg' %});height:479px;background-size: cover;">
    <div class="verticalHouse">
      <h1 class="banner_text up"> Aprende a comer y dile adiós a las dietas </h1>
      <a href="/contacto" class="up read_more_btn" style="width:185px !important;">Paquetes y servicios</a>
    </div>
  </div>
  <!--<div style="background: url({% static 'img/slider/carrousel_1.jpg' %});">
    <div class="backdrop"></div>
    <div class="imagesData" ></div>
    <div class="verticalHouse">
      <h1 class="banner_text up"> No se trata de comer menos</h1>
      <p class="sub_head up"> se trata de comer mejor </p>
      <a href="/contacto" class="up read_more_btn">Agenda tu cita</a>
    </div>
  </div>-->
</div>

nutriologa/templates/partials/footer.html
{% load static from staticfiles %}
<!-- footer -->
<script>
  function sendNewsletterEmail(params) {
    var url = "/newsletter/",
      myform = document.getElementById("correo");

    url = "http://alegpaez.com/newsletter/";
    $.ajax({
      url: url,
      data: {email:myform.value},
      type: 'POST',
      success: function (result) {
        // do something with the result
        event.preventDefault();
        if (result.status === "subscribed") {
          document.getElementById("newsLetter").reset();
          noty({text: 'Listo, espera las últimas noticias'});
        } else {
          if (result.title === "Member Exists") {
            noty({text: 'El correo ya existe, intenta con otro'});
          } else {
            noty({text: 'El correo no es válido, intenta con otro'});
          }
        }
      }
    });
  }
</script>
<paper-toast id='notifications'></paper-toast>
<footer class="bg-footer myconatiner reducePaddingInMovil">
	<div class="footer_logo">
		<img class="logo_img footerAdjustImage" src="{% static 'img/footer-img/group-20@3x.png'%}">
	</div>
	<div class="footer">
		<div class="custom-row">
			<div class="left_container">
				<p class="text_wg"> Síguenos en: </p>
				<a href="https://www.facebook.com/Nutri%C3%B3loga-Alejandra-G-P%C3%A1ez-925726230813208/" target='_blank'><img class="footer_icon special-margin" src="{% static 'img/icons/icon@3x.png'%}"> </a>
				<a href="https://www.instagram.com/nutriologa.alegpaez/" target='_blank'><img class="footer_icon" src="{% static 'img/icons/group-3@3x.png'%}"> </a>
			</div>
			<div class="center_container">
				<div class="wg_main">
					<img class="footer_icon2 logo_img_secondary" src="{% static 'img/footer-img/logo-bco-08.png'%}">
					<p class="footer_caption">  © Alejandra Gutiérrez 2017 Todos los <br> derechos reservados </p>
				</div>
			</div>
			<div class="right_container">
				<div class="form_head">
					<p class="subscribe"> Suscríbete a nuestro Newsletter </p>
				</div>
				<div class="footer_form">
					<form class="form footer_form" onsubmit="sendNewsletterEmail(); return false;" id='newsLetter'>
						<div class="input_text">
							<input required type="form_sub" class="form-control1" id="correo" placeholder="Correo electrónico">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</footer>

nutriologa/templates/partials/navbar.html
{% load static from staticfiles %}
<script>
$(document).ready(function() {
	$("body").click(function(event) {
		if (event.target.tagName === 'I') {
			slide();
		} else {
			if (event.target.tagName !== 'NAV' && !event.target.classList.contains('hamburger'))
			close();
		}
  });
	$("body").bind( "touchstart", function(event) {
		console.log(event.target, '--------');
		if (event.target.id === 'bars') {
			slide();
		} else {
			if (event.target.tagName !== 'UL')
				close();
		}
	});
});
function close () {
	if (document.querySelector('#hamburgerMenu').classList.contains('showMenu')) {
		document.querySelector('#hamburgerMenu').classList.add('slideOutRight');
		document.querySelector('#hamburgerMenu').classList.remove('slideInRight');
		setTimeout(function () {
			document.querySelector('#hamburgerMenuIcon').classList.add('hiddeOnWeb');
			document.querySelector('#imgMenu').classList.add('hiddeOnWeb');
			document.querySelector('#principalHeader').classList.remove('hiddeInMobil');
			document.querySelector('#hamburgerMenu').classList.remove('showMenu');
			document.querySelector('#mainNav').classList.remove('customHamburgerStyle');
		}, 500);
	}
}
function slide() {
	if (document.querySelector('#hamburgerMenu').classList.contains('showMenu')) {
		document.querySelector('#hamburgerMenu').classList.add('slideOutRight');
		document.querySelector('#hamburgerMenu').classList.remove('slideInRight');
		setTimeout(function () {
			document.querySelector('#hamburgerMenuIcon').classList.add('hiddeOnWeb');
			document.querySelector('#imgMenu').classList.add('hiddeOnWeb');
			document.querySelector('#principalHeader').classList.remove('hiddeInMobil');
			document.querySelector('#hamburgerMenu').classList.remove('showMenu');
			document.querySelector('#mainNav').classList.remove('customHamburgerStyle');
		}, 500);
	} else {

		document.querySelector('#principalHeader').classList.add('hiddeInMobil');
		document.querySelector('#hamburgerMenu').classList.add('slideInRight');
		document.querySelector('#hamburgerMenu').classList.add('showMenu');
		document.querySelector('#hamburgerMenu').classList.remove('slideOutRight');
		document.querySelector('#mainNav').classList.add('customHamburgerStyle');
		document.querySelector('#hamburgerMenuIcon').classList.remove('hiddeOnWeb');
		document.querySelector('#imgMenu').classList.remove('hiddeOnWeb');
	}
}
</script>
<nav id="mainNav" class="navbar navbar-default myconatiner navbar-fixed-top">
	<!-- homepage navbar -->
	<div class="container nav_container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header" id="principalHeader">
            <button type="button" class="navbar-toggle collapsed" onclick="">
                <span class="sr-only">Toggle navigation</span><i class="fa fa-bars"></i>
            </button>
            <div class="cherry_wrapper">
            	<a class="navbar-brand page-scroll" href="{% url 'landing:home' %}">
								{% if request.path == '/' %}
									<img src="{% static 'img/logo/logo-alegpaez-06@3x.png'%}" class="mobilLogoAdjust" id='removePosition'>
								{% else %}
									<img src="{% static 'img/logo/logo-alegpaez-06@3x.png'%}">
								{% endif %}
							</a>
            </div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="hamburger animated" id="hamburgerMenu">
						{% if request.path == '/' %}
							<ul class="nav navbar-nav marginCustomTop" id='fixedAction'>
						{% else %}
							<ul class="nav navbar-nav">
						{% endif %}
									<li class="hamburgerMenuIcon hiddeOnWeb" id="hamburgerMenuIcon">
										<a class="" onclick="slide()">
												<span class="sr-only">Toggle navigation</span><i class="fa fa-bars"></i>
										</a>
									</li>
								{% if request.path == '/' %}
									<li class="select selectChange">
										<a class="page-scroll" href="{% url 'landing:home'%}">Inicio</a>
									</li>
								{% else %}
									<li>
										<a class="page-scroll" href="{% url 'landing:home'%}">Inicio</a>
									</li>
								{% endif %}
								{% if request.path == '/recetas/' %}
                	<li class="select">
										<a class="page-scroll" href="{% url 'landing:recetas'%}">Recetas</a>
                	</li>
								{% else %}
									<li>
										<a class="page-scroll" href="{% url 'landing:recetas'%}">Recetas</a>
									</li>
								{% endif %}
								{% if request.path == '/videos/' %}
                	<li class="select">
										<a class="page-scroll" href="{% url 'landing:videos'%}">Videos</a>
                	</li>
								{% else %}
									<li>
										<a class="page-scroll" href="{% url 'landing:videos'%}">Videos</a>
									</li>
								{% endif %}
								{% if request.path == '/servicios/' %}
									<li class="select">
										<a class="page-scroll" href="{% url 'landing:servicios'%}">Servicios</a>
									</li>
								{% else %}
									<li>
										<a class="page-scroll" href="{% url 'landing:servicios'%}">Servicios</a>
									</li>
								{% endif %}
								{% if request.path == '/acerca/' %}
									<li class="select">
										<a class="page-scroll" href="{% url 'landing:acerca'%}">Acerca de mi</a>
									</li>
								{% else %}
									<li>
										<a class="page-scroll" href="{% url 'landing:acerca'%}">Acerca de mi</a>
									</li>
								{% endif %}
                <li>
                    <a class="page-scroll" href="http://blog.alegpaez.com/">Blog</a>
                </li>
								{% if request.path == '/contacto/' %}
									<li class="select">
										<a class="page-scroll" href="{% url 'landing:contacto'%}">Contacto</a>
									</li>
								{% else %}
									<li>
										<a class="page-scroll" href="{% url 'landing:contacto'%}">Contacto</a>
									</li>
								{% endif %}
								<li class="hiddeOnWeb" id="imgMenu">
									<a href="{% url 'landing:home' %}"><img class="miniImage" src="{% static 'img/logo/logo-alegpaez-06@3x.png'%}"></a>
								</li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
    <!-- /homepage navbar -->
</nav>